// Vocabulary data extracted from the monolithic HTML
export const vocabulary = {
  nouns: [
    { id: 1, level: 'A1', word: 'Haus', article: 'das', plural: 'Häuser', english: 'house', details: 'Nouns ending in -us, -ma, -um, -ment, -lein, -chen are often neuter (das). Many one-syllable nouns take an umlaut and "-er" in the plural.' },
    { id: 2, level: 'A1', word: 'Apfel', article: 'der', plural: 'Äpfel', english: 'apple', details: 'Masculine nouns often have plurals with an umlaut and no ending, or just an umlaut.' },
    { id: 3, level: 'A1', word: 'Frau', article: 'die', plural: 'Frauen', english: 'woman/Mrs.', details: 'Feminine nouns often form the plural by adding "-en" or "-n".' },
    { id: 8, level: 'A2', word: 'Regierung', article: 'die', plural: 'Regierungen', english: 'government', details: 'Nouns ending in -ung, -heit, -keit, -schaft, -ei are always feminine (die) and add "-en" in the plural.' },
    { id: 9, level: 'A2', word: 'Flughafen', article: 'der', plural: 'Flughäfen', english: 'airport', details: 'Compound nouns take the gender of the last word (der Hafen). The plural often follows the last word\'s plural form.' },
  ],
  verbs: [
    { id: 11, level: 'A1', infinitive: 'sein', type: 'irregular', conjugation: {ich: 'bin', du: 'bist', 'er/sie/es': 'ist', wir: 'sind', ihr: 'seid', 'sie/Sie': 'sind'}, english: 'to be', details: '"sein" is a highly irregular verb. Its conjugation must be memorized.' },
    { id: 12, level: 'A1', infinitive: 'haben', type: 'irregular', conjugation: {ich: 'habe', du: 'hast', 'er/sie/es': 'hat', wir: 'haben', ihr: 'habt', 'sie/Sie': 'haben'}, english: 'to have', details: '"haben" is an irregular verb. Note the change from "b" to "s" and "t" in the du and er/sie/es forms.' },
    { id: 13, level: 'A1', infinitive: 'sprechen', type: 'irregular', conjugation: {ich: 'spreche', du: 'sprichst', 'er/sie/es': 'spricht', wir: 'sprechen', ihr: 'sprecht', 'sie/Sie': 'sprechen'}, english: 'to speak', details: 'This is a stem-changing irregular verb. The vowel "e" changes to "i" in the du and er/sie/es forms.' },
    { id: 14, level: 'A1', infinitive: 'gehen', type: 'regular', conjugation: {ich: 'gehe', du: 'gehst', 'er/sie/es': 'geht', wir: 'gehen', ihr: 'geht', 'sie/Sie': 'gehen'}, english: 'to go', details: '"gehen" follows the standard pattern for regular verbs in the present tense.' },
    { id: 15, level: 'A2', infinitive: 'anrufen', type: 'separable', conjugation: {ich: 'rufe an', du: 'rufst an', 'er/sie/es': 'ruft an', wir: 'rufen an', ihr: 'ruft an', 'sie/Sie': 'rufen an'}, english: 'to call (phone)', details: '"anrufen" is a separable verb. The prefix "an-" goes to the end of the clause in the present tense.' },
  ],
  modalVerbs: [
    { id: 1001, level: 'A1', infinitive: 'können', english: 'can, to be able to', pronunciation: 'KÖN-nen',
      conjugation: {ich: 'kann', du: 'kannst', 'er/sie/es': 'kann', wir: 'können', ihr: 'könnt', 'sie/Sie': 'können'},
      acceptedMeanings: ['can','be able to','able'],
      example: {de: 'Ich kann schwimmen.', en: 'I can swim.'}, details: '"können" expresses ability. In polite requests, learners often use "könnten" (Konjunktiv II).'},
    { id: 1002, level: 'A1', infinitive: 'müssen', english: 'must, to have to', pronunciation: 'MÜS-sen',
      conjugation: {ich: 'muss', du: 'musst', 'er/sie/es': 'muss', wir: 'müssen', ihr: 'müsst', 'sie/Sie': 'müssen'},
      acceptedMeanings: ['must','have to','need to'],
      example: {de: 'Ich muss lernen.', en: 'I must study.'}, details: '"müssen" indicates obligation or necessity. Context distinguishes strong obligation vs. external requirement.'},
    { id: 1003, level: 'A1', infinitive: 'dürfen', english: 'may, to be allowed to', pronunciation: 'DÜR-fen',
      conjugation: {ich: 'darf', du: 'darfst', 'er/sie/es': 'darf', wir: 'dürfen', ihr: 'dürft', 'sie/Sie': 'dürfen'},
      acceptedMeanings: ['may','be allowed to','allowed'],
      example: {de: 'Darf ich gehen?', en: 'May I go?'}, details: '"dürfen" expresses permission. In negative contexts it can indicate prohibition.'},
    { id: 1004, level: 'A1', infinitive: 'sollen', english: 'should, to be supposed to', pronunciation: 'SOL-len',
      conjugation: {ich: 'soll', du: 'sollst', 'er/sie/es': 'soll', wir: 'sollen', ihr: 'sollt', 'sie/Sie': 'sollen'},
      acceptedMeanings: ['should','ought to'],
      example: {de: 'Ich soll mehr Gemüse essen.', en: 'I should eat more vegetables.'}, details: '"sollen" often indicates advice or reported obligations.'},
    { id: 1005, level: 'A1', infinitive: 'wollen', english: 'want to', pronunciation: 'WOL-len',
      conjugation: {ich: 'will', du: 'willst', 'er/sie/es': 'will', wir: 'wollen', ihr: 'wollt', 'sie/Sie': 'wollen'},
      acceptedMeanings: ['want','want to','would like'],
      example: {de: 'Ich will nach Berlin fahren.', en: 'I want to go to Berlin.'}, details: '"wollen" expresses desire or intention.'},
    { id: 1006, level: 'A1', infinitive: 'mögen', english: 'to like', pronunciation: 'MÖ-gen',
      conjugation: {ich: 'mag', du: 'magst', 'er/sie/es': 'mag', wir: 'mögen', ihr: 'mögt', 'sie/Sie': 'mögen'},
      acceptedMeanings: ['like','to like'],
      example: {de: 'Ich mag Schokolade.', en: 'I like chocolate.'}, details: '"mögen" expresses liking. For polite requests one often uses "möchten".' }
  ],
  irregularVerbs: [
    { id: 2001, level: 'A1', infinitive: 'sein', english: 'to be', pronunciation: 'ZINE',
      conjugation: {ich: 'bin', du: 'bist', 'er/sie/es': 'ist', wir: 'sind', ihr: 'seid', 'sie/Sie': 'sind'},
      partizipII: 'gewesen', perfectAux: 'sein',
      acceptedMeanings: ['be','to be','am','is','are'],
      example: {de: 'Ich bin Student.', en: 'I am a student.'},
      details: '"sein" is the most irregular verb in German. It uses "sein" as auxiliary in perfect tense. Essential for existence, identity, and location.'},
    { id: 2002, level: 'A1', infinitive: 'haben', english: 'to have', pronunciation: 'HAH-ben',
      conjugation: {ich: 'habe', du: 'hast', 'er/sie/es': 'hat', wir: 'haben', ihr: 'habt', 'sie/Sie': 'haben'},
      partizipII: 'gehabt', perfectAux: 'haben',
      acceptedMeanings: ['have','to have','has'],
      example: {de: 'Ich habe ein Auto.', en: 'I have a car.'},
      details: '"haben" is irregular in du/er forms. Used as auxiliary verb for most perfect tenses. Essential for possession and perfect tense formation.'},
    { id: 2003, level: 'A1', infinitive: 'werden', english: 'to become, will', pronunciation: 'VER-den',
      conjugation: {ich: 'werde', du: 'wirst', 'er/sie/es': 'wird', wir: 'werden', ihr: 'werdet', 'sie/Sie': 'werden'},
      partizipII: 'geworden', perfectAux: 'sein',
      acceptedMeanings: ['become','will','get','turn into'],
      example: {de: 'Ich werde Arzt.', en: 'I will become a doctor.'},
      details: '"werden" is used for future tense, passive voice, and meaning "to become". Highly irregular with stem changes.'},
    { id: 2004, level: 'A1', infinitive: 'gehen', english: 'to go', pronunciation: 'GAY-en',
      conjugation: {ich: 'gehe', du: 'gehst', 'er/sie/es': 'geht', wir: 'gehen', ihr: 'geht', 'sie/Sie': 'gehen'},
      partizipII: 'gegangen', perfectAux: 'sein',
      acceptedMeanings: ['go','walk','leave'],
      example: {de: 'Ich gehe zur Schule.', en: 'I go to school.'},
      details: '"gehen" uses "sein" as auxiliary. Essential verb for movement and many idiomatic expressions.'},
    { id: 2005, level: 'A1', infinitive: 'kommen', english: 'to come', pronunciation: 'KOM-men',
      conjugation: {ich: 'komme', du: 'kommst', 'er/sie/es': 'kommt', wir: 'kommen', ihr: 'kommt', 'sie/Sie': 'kommen'},
      partizipII: 'gekommen', perfectAux: 'sein',
      acceptedMeanings: ['come','arrive'],
      example: {de: 'Ich komme aus Deutschland.', en: 'I come from Germany.'},
      details: '"kommen" uses "sein" as auxiliary. Used for origin, arrival, and many phrasal meanings.'},
    { id: 2006, level: 'A1', infinitive: 'sehen', english: 'to see', pronunciation: 'ZAY-en',
      conjugation: {ich: 'sehe', du: 'siehst', 'er/sie/es': 'sieht', wir: 'sehen', ihr: 'seht', 'sie/Sie': 'sehen'},
      partizipII: 'gesehen', perfectAux: 'haben',
      acceptedMeanings: ['see','look','watch'],
      example: {de: 'Ich sehe einen Film.', en: 'I see/watch a movie.'},
      details: 'Stem-changing verb: e→ie in du/er forms. One of the most common irregular verbs.'},
    { id: 2007, level: 'A1', infinitive: 'geben', english: 'to give', pronunciation: 'GAY-ben',
      conjugation: {ich: 'gebe', du: 'gibst', 'er/sie/es': 'gibt', wir: 'geben', ihr: 'gebt', 'sie/Sie': 'geben'},
      partizipII: 'gegeben', perfectAux: 'haben',
      acceptedMeanings: ['give','provide'],
      example: {de: 'Ich gebe dir das Buch.', en: 'I give you the book.'},
      details: 'Stem-changing verb: e→i in du/er forms. "Es gibt" means "there is/are".'},
    { id: 2008, level: 'A1', infinitive: 'nehmen', english: 'to take', pronunciation: 'NAY-men',
      conjugation: {ich: 'nehme', du: 'nimmst', 'er/sie/es': 'nimmt', wir: 'nehmen', ihr: 'nehmt', 'sie/Sie': 'nehmen'},
      partizipII: 'genommen', perfectAux: 'haben',
      acceptedMeanings: ['take','accept'],
      example: {de: 'Ich nehme den Bus.', en: 'I take the bus.'},
      details: 'Stem-changing verb: e→i in du/er forms. Very common in daily usage.'},
    { id: 2009, level: 'A1', infinitive: 'essen', english: 'to eat', pronunciation: 'ES-sen',
      conjugation: {ich: 'esse', du: 'isst', 'er/sie/es': 'isst', wir: 'essen', ihr: 'esst', 'sie/Sie': 'essen'},
      partizipII: 'gegessen', perfectAux: 'haben',
      acceptedMeanings: ['eat'],
      example: {de: 'Ich esse Pizza.', en: 'I eat pizza.'},
      details: 'Stem-changing verb: e→i in du/er forms. Double "s" in conjugated forms.'},
    { id: 2010, level: 'A1', infinitive: 'trinken', english: 'to drink', pronunciation: 'TRIN-ken',
      conjugation: {ich: 'trinke', du: 'trinkst', 'er/sie/es': 'trinkt', wir: 'trinken', ihr: 'trinkt', 'sie/Sie': 'trinken'},
      partizipII: 'getrunken', perfectAux: 'haben',
      acceptedMeanings: ['drink'],
      example: {de: 'Ich trinke Wasser.', en: 'I drink water.'},
      details: 'Strong verb with vowel change in Partizip II: i→u→u pattern.'},
    { id: 2011, level: 'A2', infinitive: 'fahren', english: 'to drive, travel', pronunciation: 'FAH-ren',
      conjugation: {ich: 'fahre', du: 'fährst', 'er/sie/es': 'fährt', wir: 'fahren', ihr: 'fahrt', 'sie/Sie': 'fahren'},
      partizipII: 'gefahren', perfectAux: 'sein',
      acceptedMeanings: ['drive','travel','go by vehicle'],
      example: {de: 'Ich fahre mit dem Auto.', en: 'I drive by car.'},
      details: 'Stem-changing verb: a→ä in du/er forms. Uses "sein" when indicating movement.'},
    { id: 2012, level: 'A2', infinitive: 'lesen', english: 'to read', pronunciation: 'LAY-zen',
      conjugation: {ich: 'lese', du: 'liest', 'er/sie/es': 'liest', wir: 'lesen', ihr: 'lest', 'sie/Sie': 'lesen'},
      partizipII: 'gelesen', perfectAux: 'haben',
      acceptedMeanings: ['read'],
      example: {de: 'Ich lese ein Buch.', en: 'I read a book.'},
      details: 'Stem-changing verb: e→ie in du/er forms. Essential for academic contexts.'},
    { id: 2013, level: 'A2', infinitive: 'schreiben', english: 'to write', pronunciation: 'SHRY-ben',
      conjugation: {ich: 'schreibe', du: 'schreibst', 'er/sie/es': 'schreibt', wir: 'schreiben', ihr: 'schreibt', 'sie/Sie': 'schreiben'},
      partizipII: 'geschrieben', perfectAux: 'haben',
      acceptedMeanings: ['write'],
      example: {de: 'Ich schreibe einen Brief.', en: 'I write a letter.'},
      details: 'Strong verb with vowel change: ei→ie in Partizip II. Essential for communication.'},
    { id: 2014, level: 'A2', infinitive: 'sprechen', english: 'to speak', pronunciation: 'SHPREH-khen',
      conjugation: {ich: 'spreche', du: 'sprichst', 'er/sie/es': 'spricht', wir: 'sprechen', ihr: 'sprecht', 'sie/Sie': 'sprechen'},
      partizipII: 'gesprochen', perfectAux: 'haben',
      acceptedMeanings: ['speak','talk'],
      example: {de: 'Ich spreche Deutsch.', en: 'I speak German.'},
      details: 'Stem-changing verb: e→i in du/er forms. Essential for communication.'},
    { id: 2015, level: 'A2', infinitive: 'finden', english: 'to find', pronunciation: 'FIN-den',
      conjugation: {ich: 'finde', du: 'findest', 'er/sie/es': 'findet', wir: 'finden', ihr: 'findet', 'sie/Sie': 'finden'},
      partizipII: 'gefunden', perfectAux: 'haben',
      acceptedMeanings: ['find','think','consider'],
      example: {de: 'Ich finde den Schlüssel.', en: 'I find the key.'},
      details: 'Strong verb with vowel change: i→u in Partizip II. Also means "to think" in some contexts.'},
    { id: 2016, level: 'A2', infinitive: 'helfen', english: 'to help', pronunciation: 'HEL-fen',
      conjugation: {ich: 'helfe', du: 'hilfst', 'er/sie/es': 'hilft', wir: 'helfen', ihr: 'helft', 'sie/Sie': 'helfen'},
      partizipII: 'geholfen', perfectAux: 'haben',
      acceptedMeanings: ['help','assist'],
      example: {de: 'Ich helfe dir.', en: 'I help you.'},
      details: 'Stem-changing verb: e→i in du/er forms. Takes dative object.'},
    { id: 2017, level: 'A2', infinitive: 'laufen', english: 'to run, walk', pronunciation: 'LOW-fen',
      conjugation: {ich: 'laufe', du: 'läufst', 'er/sie/es': 'läuft', wir: 'laufen', ihr: 'lauft', 'sie/Sie': 'laufen'},
      partizipII: 'gelaufen', perfectAux: 'sein',
      acceptedMeanings: ['run','walk','function'],
      example: {de: 'Ich laufe im Park.', en: 'I run in the park.'},
      details: 'Stem-changing verb: au→äu in du/er forms. Uses "sein" auxiliary for movement.'},
    { id: 2018, level: 'A2', infinitive: 'schlafen', english: 'to sleep', pronunciation: 'SHLAH-fen',
      conjugation: {ich: 'schlafe', du: 'schläfst', 'er/sie/es': 'schläft', wir: 'schlafen', ihr: 'schlaft', 'sie/Sie': 'schlafen'},
      partizipII: 'geschlafen', perfectAux: 'haben',
      acceptedMeanings: ['sleep'],
      example: {de: 'Ich schlafe acht Stunden.', en: 'I sleep eight hours.'},
      details: 'Stem-changing verb: a→ä in du/er forms. Essential daily activity verb.'},
    { id: 2019, level: 'A2', infinitive: 'wissen', english: 'to know (facts)', pronunciation: 'VIS-sen',
      conjugation: {ich: 'weiß', du: 'weißt', 'er/sie/es': 'weiß', wir: 'wissen', ihr: 'wisst', 'sie/Sie': 'wissen'},
      partizipII: 'gewusst', perfectAux: 'haben',
      acceptedMeanings: ['know','know facts'],
      example: {de: 'Ich weiß die Antwort.', en: 'I know the answer.'},
      details: 'Highly irregular verb. Distinguishes factual knowledge from "kennen" (knowing people/places).'},
    { id: 2020, level: 'A2', infinitive: 'bringen', english: 'to bring', pronunciation: 'BRING-en',
      conjugation: {ich: 'bringe', du: 'bringst', 'er/sie/es': 'bringt', wir: 'bringen', ihr: 'bringt', 'sie/Sie': 'bringen'},
      partizipII: 'gebracht', perfectAux: 'haben',
      acceptedMeanings: ['bring','take to'],
      example: {de: 'Ich bringe dir Kaffee.', en: 'I bring you coffee.'},
      details: 'Mixed verb: regular present, irregular past forms. Very common in daily usage.'}
  ]
};


