// Vocabulary data extracted from the monolithic HTML
export const vocabulary = {
  nouns: [
    { id: 1, level: 'A1', word: 'Haus', article: 'das', plural: 'Häuser', english: 'house', details: 'Nouns ending in -us, -ma, -um, -ment, -lein, -chen are often neuter (das). Many one-syllable nouns take an umlaut and "-er" in the plural.' },
    { id: 2, level: 'A1', word: 'Apfel', article: 'der', plural: 'Äpfel', english: 'apple', details: 'Masculine nouns often have plurals with an umlaut and no ending, or just an umlaut.' },
    { id: 3, level: 'A1', word: 'Frau', article: 'die', plural: 'Frauen', english: 'woman/Mrs.', details: 'Feminine nouns often form the plural by adding "-en" or "-n".' },
    { id: 8, level: 'A2', word: 'Regierung', article: 'die', plural: 'Regierungen', english: 'government', details: 'Nouns ending in -ung, -heit, -keit, -schaft, -ei are always feminine (die) and add "-en" in the plural.' },
    { id: 9, level: 'A2', word: 'Flughafen', article: 'der', plural: 'Flughäfen', english: 'airport', details: 'Compound nouns take the gender of the last word (der Hafen). The plural often follows the last word\'s plural form.' },
  ],
  verbs: [
    { id: 11, level: 'A1', infinitive: 'sein', type: 'irregular', conjugation: {ich: 'bin', du: 'bist', 'er/sie/es': 'ist', wir: 'sind', ihr: 'seid', 'sie/Sie': 'sind'}, english: 'to be', details: '"sein" is a highly irregular verb. Its conjugation must be memorized.' },
    { id: 12, level: 'A1', infinitive: 'haben', type: 'irregular', conjugation: {ich: 'habe', du: 'hast', 'er/sie/es': 'hat', wir: 'haben', ihr: 'habt', 'sie/Sie': 'haben'}, english: 'to have', details: '"haben" is an irregular verb. Note the change from "b" to "s" and "t" in the du and er/sie/es forms.' },
    { id: 13, level: 'A1', infinitive: 'sprechen', type: 'irregular', conjugation: {ich: 'spreche', du: 'sprichst', 'er/sie/es': 'spricht', wir: 'sprechen', ihr: 'sprecht', 'sie/Sie': 'sprechen'}, english: 'to speak', details: 'This is a stem-changing irregular verb. The vowel "e" changes to "i" in the du and er/sie/es forms.' },
    { id: 14, level: 'A1', infinitive: 'gehen', type: 'regular', conjugation: {ich: 'gehe', du: 'gehst', 'er/sie/es': 'geht', wir: 'gehen', ihr: 'geht', 'sie/Sie': 'gehen'}, english: 'to go', details: '"gehen" follows the standard pattern for regular verbs in the present tense.' },
    { id: 15, level: 'A2', infinitive: 'anrufen', type: 'separable', conjugation: {ich: 'rufe an', du: 'rufst an', 'er/sie/es': 'ruft an', wir: 'rufen an', ihr: 'ruft an', 'sie/Sie': 'rufen an'}, english: 'to call (phone)', details: '"anrufen" is a separable verb. The prefix "an-" goes to the end of the clause in the present tense.' },
  ],
  modalVerbs: [
    { id: 1001, level: 'A1', infinitive: 'können', english: 'can, to be able to', pronunciation: 'KÖN-nen',
      conjugation: {ich: 'kann', du: 'kannst', 'er/sie/es': 'kann', wir: 'können', ihr: 'könnt', 'sie/Sie': 'können'},
      acceptedMeanings: ['can','be able to','able'],
      example: {de: 'Ich kann schwimmen.', en: 'I can swim.'}, details: '"können" expresses ability. In polite requests, learners often use "könnten" (Konjunktiv II).'},
    { id: 1002, level: 'A1', infinitive: 'müssen', english: 'must, to have to', pronunciation: 'MÜS-sen',
      conjugation: {ich: 'muss', du: 'musst', 'er/sie/es': 'muss', wir: 'müssen', ihr: 'müsst', 'sie/Sie': 'müssen'},
      acceptedMeanings: ['must','have to','need to'],
      example: {de: 'Ich muss lernen.', en: 'I must study.'}, details: '"müssen" indicates obligation or necessity. Context distinguishes strong obligation vs. external requirement.'},
    { id: 1003, level: 'A1', infinitive: 'dürfen', english: 'may, to be allowed to', pronunciation: 'DÜR-fen',
      conjugation: {ich: 'darf', du: 'darfst', 'er/sie/es': 'darf', wir: 'dürfen', ihr: 'dürft', 'sie/Sie': 'dürfen'},
      acceptedMeanings: ['may','be allowed to','allowed'],
      example: {de: 'Darf ich gehen?', en: 'May I go?'}, details: '"dürfen" expresses permission. In negative contexts it can indicate prohibition.'},
    { id: 1004, level: 'A1', infinitive: 'sollen', english: 'should, to be supposed to', pronunciation: 'SOL-len',
      conjugation: {ich: 'soll', du: 'sollst', 'er/sie/es': 'soll', wir: 'sollen', ihr: 'sollt', 'sie/Sie': 'sollen'},
      acceptedMeanings: ['should','ought to'],
      example: {de: 'Ich soll mehr Gemüse essen.', en: 'I should eat more vegetables.'}, details: '"sollen" often indicates advice or reported obligations.'},
    { id: 1005, level: 'A1', infinitive: 'wollen', english: 'want to', pronunciation: 'WOL-len',
      conjugation: {ich: 'will', du: 'willst', 'er/sie/es': 'will', wir: 'wollen', ihr: 'wollt', 'sie/Sie': 'wollen'},
      acceptedMeanings: ['want','want to','would like'],
      example: {de: 'Ich will nach Berlin fahren.', en: 'I want to go to Berlin.'}, details: '"wollen" expresses desire or intention.'},
    { id: 1006, level: 'A1', infinitive: 'mögen', english: 'to like', pronunciation: 'MÖ-gen',
      conjugation: {ich: 'mag', du: 'magst', 'er/sie/es': 'mag', wir: 'mögen', ihr: 'mögt', 'sie/Sie': 'mögen'},
      acceptedMeanings: ['like','to like'],
      example: {de: 'Ich mag Schokolade.', en: 'I like chocolate.'}, details: '"mögen" expresses liking. For polite requests one often uses "möchten".' },
    { id: 1007, level: 'A2', infinitive: 'möchten', english: 'would like to', pronunciation: 'MÖCH-ten',
      conjugation: {ich: 'möchte', du: 'möchtest', 'er/sie/es': 'möchte', wir: 'möchten', ihr: 'möchtet', 'sie/Sie': 'möchten'},
      acceptedMeanings: ['would like','would like to','want politely'],
      example: {de: 'Ich möchte einen Kaffee.', en: 'I would like a coffee.'}, details: '"möchten" is the polite form of "wollen" and is used for polite requests.' },
    { id: 1008, level: 'A2', infinitive: 'können', english: 'can, to be able to', pronunciation: 'KÖN-nen',
      conjugation: {ich: 'kann', du: 'kannst', 'er/sie/es': 'kann', wir: 'können', ihr: 'könnt', 'sie/Sie': 'können'},
      acceptedMeanings: ['can','be able to','able'],
      example: {de: 'Kann ich Ihnen helfen?', en: 'Can I help you?'}, details: 'A2 level focuses on polite forms and more complex usage patterns.' }
  ],
  separableVerbs: [
    { id: 3001, level: 'A1', infinitive: 'anrufen', english: 'to call (phone)', pronunciation: 'AN-rufen',
      conjugation: {ich: 'rufe an', du: 'rufst an', 'er/sie/es': 'ruft an', wir: 'rufen an', ihr: 'ruft an', 'sie/Sie': 'rufen an'},
      prefix: 'an', baseVerb: 'rufen',
      acceptedMeanings: ['call','phone','ring'],
      example: {de: 'Ich rufe dich an.', en: 'I call you.'},
      details: 'The prefix "an-" separates and goes to the end of the clause in present tense. Used for making phone calls.'},
    { id: 3002, level: 'A1', infinitive: 'aufstehen', english: 'to get up, stand up', pronunciation: 'AUF-shtay-en',
      conjugation: {ich: 'stehe auf', du: 'stehst auf', 'er/sie/es': 'steht auf', wir: 'stehen auf', ihr: 'steht auf', 'sie/Sie': 'stehen auf'},
      prefix: 'auf', baseVerb: 'stehen',
      acceptedMeanings: ['get up','stand up','rise'],
      example: {de: 'Ich stehe um 7 Uhr auf.', en: 'I get up at 7 o\'clock.'},
      details: 'The prefix "auf-" separates and goes to the end. Essential for daily routines.'},
    { id: 3003, level: 'A1', infinitive: 'ausgehen', english: 'to go out', pronunciation: 'AUWS-gay-en',
      conjugation: {ich: 'gehe aus', du: 'gehst aus', 'er/sie/es': 'geht aus', wir: 'gehen aus', ihr: 'geht aus', 'sie/Sie': 'gehen aus'},
      prefix: 'aus', baseVerb: 'gehen',
      acceptedMeanings: ['go out','go outside'],
      example: {de: 'Wir gehen heute Abend aus.', en: 'We are going out tonight.'},
      details: 'The prefix "aus-" separates and goes to the end. Used for social activities.'},
    { id: 3004, level: 'A1', infinitive: 'einkaufen', english: 'to shop, buy', pronunciation: 'INE-kow-fen',
      conjugation: {ich: 'kaufe ein', du: 'kaufst ein', 'er/sie/es': 'kauft ein', wir: 'kaufen ein', ihr: 'kauft ein', 'sie/Sie': 'kaufen ein'},
      prefix: 'ein', baseVerb: 'kaufen',
      acceptedMeanings: ['shop','buy','go shopping'],
      example: {de: 'Ich kaufe im Supermarkt ein.', en: 'I shop at the supermarket.'},
      details: 'The prefix "ein-" separates and goes to the end. Essential for shopping activities.'},
    { id: 3005, level: 'A1', infinitive: 'fernsehen', english: 'to watch TV', pronunciation: 'FAIRN-zay-en',
      conjugation: {ich: 'sehe fern', du: 'siehst fern', 'er/sie/es': 'sieht fern', wir: 'sehen fern', ihr: 'seht fern', 'sie/Sie': 'sehen fern'},
      prefix: 'fern', baseVerb: 'sehen',
      acceptedMeanings: ['watch tv','watch television'],
      example: {de: 'Ich sehe gerne fern.', en: 'I like to watch TV.'},
      details: 'The prefix "fern-" separates and goes to the end. Used for television viewing.'},
    { id: 3006, level: 'A2', infinitive: 'abfahren', english: 'to depart, leave', pronunciation: 'AP-fah-ren',
      conjugation: {ich: 'fahre ab', du: 'fährst ab', 'er/sie/es': 'fährt ab', wir: 'fahren ab', ihr: 'fahrt ab', 'sie/Sie': 'fahren ab'},
      prefix: 'ab', baseVerb: 'fahren',
      acceptedMeanings: ['depart','leave','set off'],
      example: {de: 'Der Zug fährt um 10 Uhr ab.', en: 'The train departs at 10 o\'clock.'},
      details: 'The prefix "ab-" separates and goes to the end. Used for transportation departures.'},
    { id: 3007, level: 'A2', infinitive: 'ankommen', english: 'to arrive', pronunciation: 'AN-kom-men',
      conjugation: {ich: 'komme an', du: 'kommst an', 'er/sie/es': 'kommt an', wir: 'kommen an', ihr: 'kommt an', 'sie/Sie': 'kommen an'},
      prefix: 'an', baseVerb: 'kommen',
      acceptedMeanings: ['arrive','get to','reach'],
      example: {de: 'Wann kommst du an?', en: 'When do you arrive?'},
      details: 'The prefix "an-" separates and goes to the end. Essential for travel and meetings.'},
    { id: 3008, level: 'A2', infinitive: 'aussteigen', english: 'to get off, exit', pronunciation: 'AUWS-shty-gen',
      conjugation: {ich: 'steige aus', du: 'steigst aus', 'er/sie/es': 'steigt aus', wir: 'steigen aus', ihr: 'steigt aus', 'sie/Sie': 'steigen aus'},
      prefix: 'aus', baseVerb: 'steigen',
      acceptedMeanings: ['get off','exit','alight'],
      example: {de: 'Ich steige an der nächsten Haltestelle aus.', en: 'I get off at the next stop.'},
      details: 'The prefix "aus-" separates and goes to the end. Used for exiting vehicles.'},
    { id: 3009, level: 'A2', infinitive: 'einsteigen', english: 'to get on, board', pronunciation: 'INE-shty-gen',
      conjugation: {ich: 'steige ein', du: 'steigst ein', 'er/sie/es': 'steigt ein', wir: 'steigen ein', ihr: 'steigt ein', 'sie/Sie': 'steigen ein'},
      prefix: 'ein', baseVerb: 'steigen',
      acceptedMeanings: ['get on','board','enter vehicle'],
      example: {de: 'Ich steige in den Bus ein.', en: 'I get on the bus.'},
      details: 'The prefix "ein-" separates and goes to the end. Used for boarding vehicles.'},
    { id: 3010, level: 'A2', infinitive: 'umsteigen', english: 'to change (transport)', pronunciation: 'UM-shty-gen',
      conjugation: {ich: 'steige um', du: 'steigst um', 'er/sie/es': 'steigt um', wir: 'steigen um', ihr: 'steigt um', 'sie/Sie': 'steigen um'},
      prefix: 'um', baseVerb: 'steigen',
      acceptedMeanings: ['change','transfer','switch'],
      example: {de: 'Ich steige in Berlin um.', en: 'I change trains in Berlin.'},
      details: 'The prefix "um-" separates and goes to the end. Used for changing transportation.'}
  ],
  irregularVerbs: [
    // A1 Irregular Verbs from Goethe A2 WortListe
    { id: 2001, level: 'A1', infinitive: 'sein', english: 'to be', pronunciation: 'ZINE',
      conjugation: {ich: 'bin', du: 'bist', 'er/sie/es': 'ist', wir: 'sind', ihr: 'seid', 'sie/Sie': 'sind'},
      partizipII: 'gewesen', perfectAux: 'sein', prateritum: 'war',
      acceptedMeanings: ['be','to be','am','is','are'],
      example: {de: 'Ich bin Student.', en: 'I am a student.'},
      details: '"sein" is the most irregular verb in German. It uses "sein" as auxiliary in perfect tense. Essential for existence, identity, and location.'},
    { id: 2002, level: 'A1', infinitive: 'haben', english: 'to have', pronunciation: 'HAH-ben',
      conjugation: {ich: 'habe', du: 'hast', 'er/sie/es': 'hat', wir: 'haben', ihr: 'habt', 'sie/Sie': 'haben'},
      partizipII: 'gehabt', perfectAux: 'haben', prateritum: 'hatte',
      acceptedMeanings: ['have','to have','has'],
      example: {de: 'Ich habe ein Auto.', en: 'I have a car.'},
      details: '"haben" is irregular in du/er forms. Used as auxiliary verb for most perfect tenses. Essential for possession and perfect tense formation.'},
    { id: 2003, level: 'A1', infinitive: 'gehen', english: 'to go', pronunciation: 'GAY-en',
      conjugation: {ich: 'gehe', du: 'gehst', 'er/sie/es': 'geht', wir: 'gehen', ihr: 'geht', 'sie/Sie': 'gehen'},
      partizipII: 'gegangen', perfectAux: 'sein', prateritum: 'ging',
      acceptedMeanings: ['go','walk','leave'],
      example: {de: 'Ich gehe zur Schule.', en: 'I go to school.'},
      details: '"gehen" uses "sein" as auxiliary. Essential verb for movement and many idiomatic expressions.'},
    { id: 2004, level: 'A1', infinitive: 'kommen', english: 'to come', pronunciation: 'KOM-men',
      conjugation: {ich: 'komme', du: 'kommst', 'er/sie/es': 'kommt', wir: 'kommen', ihr: 'kommt', 'sie/Sie': 'kommen'},
      partizipII: 'gekommen', perfectAux: 'sein', prateritum: 'kam',
      acceptedMeanings: ['come','arrive'],
      example: {de: 'Ich komme aus Deutschland.', en: 'I come from Germany.'},
      details: '"kommen" uses "sein" as auxiliary. Used for origin, arrival, and many phrasal meanings.'},
    { id: 2005, level: 'A1', infinitive: 'sehen', english: 'to see', pronunciation: 'ZAY-en',
      conjugation: {ich: 'sehe', du: 'siehst', 'er/sie/es': 'sieht', wir: 'sehen', ihr: 'seht', 'sie/Sie': 'sehen'},
      partizipII: 'gesehen', perfectAux: 'haben', prateritum: 'sah',
      acceptedMeanings: ['see','look','watch'],
      example: {de: 'Ich sehe einen Film.', en: 'I see/watch a movie.'},
      details: 'Stem-changing verb: e→ie in du/er forms. One of the most common irregular verbs.'},
    { id: 2006, level: 'A1', infinitive: 'essen', english: 'to eat', pronunciation: 'ES-sen',
      conjugation: {ich: 'esse', du: 'isst', 'er/sie/es': 'isst', wir: 'essen', ihr: 'esst', 'sie/Sie': 'essen'},
      partizipII: 'gegessen', perfectAux: 'haben', prateritum: 'aß',
      acceptedMeanings: ['eat'],
      example: {de: 'Ich esse Pizza.', en: 'I eat pizza.'},
      details: 'Stem-changing verb: e→i in du/er forms. Double "s" in conjugated forms.'},
    { id: 2007, level: 'A1', infinitive: 'trinken', english: 'to drink', pronunciation: 'TRIN-ken',
      conjugation: {ich: 'trinke', du: 'trinkst', 'er/sie/es': 'trinkt', wir: 'trinken', ihr: 'trinkt', 'sie/Sie': 'trinken'},
      partizipII: 'getrunken', perfectAux: 'haben', prateritum: 'trank',
      acceptedMeanings: ['drink'],
      example: {de: 'Ich trinke Wasser.', en: 'I drink water.'},
      details: 'Strong verb with vowel change in Partizip II: i→u→u pattern.'},
    { id: 2008, level: 'A1', infinitive: 'sprechen', english: 'to speak', pronunciation: 'SHPREH-khen',
      conjugation: {ich: 'spreche', du: 'sprichst', 'er/sie/es': 'spricht', wir: 'sprechen', ihr: 'sprecht', 'sie/Sie': 'sprechen'},
      partizipII: 'gesprochen', perfectAux: 'haben', prateritum: 'sprach',
      acceptedMeanings: ['speak','talk'],
      example: {de: 'Ich spreche Deutsch.', en: 'I speak German.'},
      details: 'Stem-changing verb: e→i in du/er forms. Essential for communication.'},
    { id: 2009, level: 'A1', infinitive: 'lesen', english: 'to read', pronunciation: 'LAY-zen',
      conjugation: {ich: 'lese', du: 'liest', 'er/sie/es': 'liest', wir: 'lesen', ihr: 'lest', 'sie/Sie': 'lesen'},
      partizipII: 'gelesen', perfectAux: 'haben', prateritum: 'las',
      acceptedMeanings: ['read'],
      example: {de: 'Ich lese ein Buch.', en: 'I read a book.'},
      details: 'Stem-changing verb: e→ie in du/er forms. Essential for academic contexts.'},
    { id: 2010, level: 'A1', infinitive: 'nehmen', english: 'to take', pronunciation: 'NAY-men',
      conjugation: {ich: 'nehme', du: 'nimmst', 'er/sie/es': 'nimmt', wir: 'nehmen', ihr: 'nehmt', 'sie/Sie': 'nehmen'},
      partizipII: 'genommen', perfectAux: 'haben', prateritum: 'nahm',
      acceptedMeanings: ['take','accept'],
      example: {de: 'Ich nehme den Bus.', en: 'I take the bus.'},
      details: 'Stem-changing verb: e→i in du/er forms. Very common in daily usage.'},
    { id: 2011, level: 'A1', infinitive: 'geben', english: 'to give', pronunciation: 'GAY-ben',
      conjugation: {ich: 'gebe', du: 'gibst', 'er/sie/es': 'gibt', wir: 'geben', ihr: 'gebt', 'sie/Sie': 'geben'},
      partizipII: 'gegeben', perfectAux: 'haben', prateritum: 'gab',
      acceptedMeanings: ['give','provide'],
      example: {de: 'Ich gebe dir das Buch.', en: 'I give you the book.'},
      details: 'Stem-changing verb: e→i in du/er forms. "Es gibt" means "there is/are".'},
    { id: 2012, level: 'A1', infinitive: 'wissen', english: 'to know (fact)', pronunciation: 'VIS-sen',
      conjugation: {ich: 'weiß', du: 'weißt', 'er/sie/es': 'weiß', wir: 'wissen', ihr: 'wisst', 'sie/Sie': 'wissen'},
      partizipII: 'gewusst', perfectAux: 'haben', prateritum: 'wusste',
      acceptedMeanings: ['know','know facts'],
      example: {de: 'Ich weiß die Antwort.', en: 'I know the answer.'},
      details: 'Highly irregular verb. Distinguishes factual knowledge from "kennen" (knowing people/places).'},
    { id: 2013, level: 'A1', infinitive: 'bleiben', english: 'to stay', pronunciation: 'BLY-ben',
      conjugation: {ich: 'bleibe', du: 'bleibst', 'er/sie/es': 'bleibt', wir: 'bleiben', ihr: 'bleibt', 'sie/Sie': 'bleiben'},
      partizipII: 'geblieben', perfectAux: 'sein', prateritum: 'blieb',
      acceptedMeanings: ['stay','remain'],
      example: {de: 'Ich bleibe zu Hause.', en: 'I stay at home.'},
      details: 'Uses "sein" as auxiliary. Essential for location and duration.'},
    { id: 2014, level: 'A1', infinitive: 'fahren', english: 'to drive/go', pronunciation: 'FAH-ren',
      conjugation: {ich: 'fahre', du: 'fährst', 'er/sie/es': 'fährt', wir: 'fahren', ihr: 'fahrt', 'sie/Sie': 'fahren'},
      partizipII: 'gefahren', perfectAux: 'sein', prateritum: 'fuhr',
      acceptedMeanings: ['drive','travel','go by vehicle'],
      example: {de: 'Ich fahre mit dem Auto.', en: 'I drive by car.'},
      details: 'Stem-changing verb: a→ä in du/er forms. Uses "sein" when indicating movement.'},
    { id: 2015, level: 'A1', infinitive: 'fliegen', english: 'to fly', pronunciation: 'FLEE-gen',
      conjugation: {ich: 'fliege', du: 'fliegst', 'er/sie/es': 'fliegt', wir: 'fliegen', ihr: 'fliegt', 'sie/Sie': 'fliegen'},
      partizipII: 'geflogen', perfectAux: 'sein', prateritum: 'flog',
      acceptedMeanings: ['fly'],
      example: {de: 'Ich fliege nach Berlin.', en: 'I fly to Berlin.'},
      details: 'Uses "sein" as auxiliary. Essential for air travel.'},
    { id: 2016, level: 'A1', infinitive: 'laufen', english: 'to run', pronunciation: 'LOW-fen',
      conjugation: {ich: 'laufe', du: 'läufst', 'er/sie/es': 'läuft', wir: 'laufen', ihr: 'lauft', 'sie/Sie': 'laufen'},
      partizipII: 'gelaufen', perfectAux: 'sein', prateritum: 'lief',
      acceptedMeanings: ['run','walk','function'],
      example: {de: 'Ich laufe im Park.', en: 'I run in the park.'},
      details: 'Stem-changing verb: au→äu in du/er forms. Uses "sein" auxiliary for movement.'},
    { id: 2017, level: 'A1', infinitive: 'schlafen', english: 'to sleep', pronunciation: 'SHLAH-fen',
      conjugation: {ich: 'schlafe', du: 'schläfst', 'er/sie/es': 'schläft', wir: 'schlafen', ihr: 'schlaft', 'sie/Sie': 'schlafen'},
      partizipII: 'geschlafen', perfectAux: 'haben', prateritum: 'schlief',
      acceptedMeanings: ['sleep'],
      example: {de: 'Ich schlafe acht Stunden.', en: 'I sleep eight hours.'},
      details: 'Stem-changing verb: a→ä in du/er forms. Essential daily activity verb.'},
    { id: 2018, level: 'A1', infinitive: 'schreiben', english: 'to write', pronunciation: 'SHRY-ben',
      conjugation: {ich: 'schreibe', du: 'schreibst', 'er/sie/es': 'schreibt', wir: 'schreiben', ihr: 'schreibt', 'sie/Sie': 'schreiben'},
      partizipII: 'geschrieben', perfectAux: 'haben', prateritum: 'schrieb',
      acceptedMeanings: ['write'],
      example: {de: 'Ich schreibe einen Brief.', en: 'I write a letter.'},
      details: 'Strong verb with vowel change: ei→ie in Partizip II. Essential for communication.'},
    { id: 2019, level: 'A1', infinitive: 'finden', english: 'to find', pronunciation: 'FIN-den',
      conjugation: {ich: 'finde', du: 'findest', 'er/sie/es': 'findet', wir: 'finden', ihr: 'findet', 'sie/Sie': 'finden'},
      partizipII: 'gefunden', perfectAux: 'haben', prateritum: 'fand',
      acceptedMeanings: ['find','think','consider'],
      example: {de: 'Ich finde den Schlüssel.', en: 'I find the key.'},
      details: 'Strong verb with vowel change: i→u in Partizip II. Also means "to think" in some contexts.'},
    { id: 2020, level: 'A1', infinitive: 'bringen', english: 'to bring', pronunciation: 'BRING-en',
      conjugation: {ich: 'bringe', du: 'bringst', 'er/sie/es': 'bringt', wir: 'bringen', ihr: 'bringt', 'sie/Sie': 'bringen'},
      partizipII: 'gebracht', perfectAux: 'haben', prateritum: 'brachte',
      acceptedMeanings: ['bring','take to'],
      example: {de: 'Ich bringe dir Kaffee.', en: 'I bring you coffee.'},
      details: 'Mixed verb: regular present, irregular past forms. Very common in daily usage.'},
    { id: 2021, level: 'A1', infinitive: 'denken', english: 'to think', pronunciation: 'DEN-ken',
      conjugation: {ich: 'denke', du: 'denkst', 'er/sie/es': 'denkt', wir: 'denken', ihr: 'denkt', 'sie/Sie': 'denken'},
      partizipII: 'gedacht', perfectAux: 'haben', prateritum: 'dachte',
      acceptedMeanings: ['think'],
      example: {de: 'Ich denke an dich.', en: 'I think of you.'},
      details: 'Irregular past forms. Essential for expressing thoughts and opinions.'},
    { id: 2022, level: 'A1', infinitive: 'tun', english: 'to do', pronunciation: 'TOON',
      conjugation: {ich: 'tue', du: 'tust', 'er/sie/es': 'tut', wir: 'tun', ihr: 'tut', 'sie/Sie': 'tun'},
      partizipII: 'getan', perfectAux: 'haben', prateritum: 'tat',
      acceptedMeanings: ['do'],
      example: {de: 'Was tust du?', en: 'What are you doing?'},
      details: 'Highly irregular verb. Used for general actions and activities.'},
    { id: 2023, level: 'A1', infinitive: 'helfen', english: 'to help', pronunciation: 'HEL-fen',
      conjugation: {ich: 'helfe', du: 'hilfst', 'er/sie/es': 'hilft', wir: 'helfen', ihr: 'helft', 'sie/Sie': 'helfen'},
      partizipII: 'geholfen', perfectAux: 'haben', prateritum: 'half',
      acceptedMeanings: ['help','assist'],
      example: {de: 'Ich helfe dir.', en: 'I help you.'},
      details: 'Stem-changing verb: e→i in du/er forms. Takes dative object.'},
    { id: 2024, level: 'A1', infinitive: 'kennen', english: 'to know (person)', pronunciation: 'KEN-nen',
      conjugation: {ich: 'kenne', du: 'kennst', 'er/sie/es': 'kennt', wir: 'kennen', ihr: 'kennt', 'sie/Sie': 'kennen'},
      partizipII: 'gekannt', perfectAux: 'haben', prateritum: 'kannte',
      acceptedMeanings: ['know','know person'],
      example: {de: 'Ich kenne ihn.', en: 'I know him.'},
      details: 'Distinguishes knowing people/places from "wissen" (knowing facts).'},
    { id: 2025, level: 'A1', infinitive: 'mögen', english: 'to like', pronunciation: 'MÖ-gen',
      conjugation: {ich: 'mag', du: 'magst', 'er/sie/es': 'mag', wir: 'mögen', ihr: 'mögt', 'sie/Sie': 'mögen'},
      partizipII: 'gemocht', perfectAux: 'haben', prateritum: 'mochte',
      acceptedMeanings: ['like','to like'],
      example: {de: 'Ich mag Schokolade.', en: 'I like chocolate.'},
      details: 'Modal verb expressing liking. For polite requests one often uses "möchten".'},
    { id: 2026, level: 'A1', infinitive: 'müssen', english: 'to have to', pronunciation: 'MÜS-sen',
      conjugation: {ich: 'muss', du: 'musst', 'er/sie/es': 'muss', wir: 'müssen', ihr: 'müsst', 'sie/Sie': 'müssen'},
      partizipII: 'gemusst', perfectAux: 'haben', prateritum: 'musste',
      acceptedMeanings: ['must','have to','need to'],
      example: {de: 'Ich muss lernen.', en: 'I must study.'},
      details: 'Modal verb indicating obligation or necessity.'},
    { id: 2027, level: 'A1', infinitive: 'können', english: 'can/to be able to', pronunciation: 'KÖN-nen',
      conjugation: {ich: 'kann', du: 'kannst', 'er/sie/es': 'kann', wir: 'können', ihr: 'könnt', 'sie/Sie': 'können'},
      partizipII: 'gekonnt', perfectAux: 'haben', prateritum: 'konnte',
      acceptedMeanings: ['can','be able to','able'],
      example: {de: 'Ich kann schwimmen.', en: 'I can swim.'},
      details: 'Modal verb expressing ability. In polite requests, learners often use "könnten" (Konjunktiv II).'},
    { id: 2028, level: 'A1', infinitive: 'wollen', english: 'to want', pronunciation: 'WOL-len',
      conjugation: {ich: 'will', du: 'willst', 'er/sie/es': 'will', wir: 'wollen', ihr: 'wollt', 'sie/Sie': 'wollen'},
      partizipII: 'gewollt', perfectAux: 'haben', prateritum: 'wollte',
      acceptedMeanings: ['want','want to','would like'],
      example: {de: 'Ich will nach Berlin fahren.', en: 'I want to go to Berlin.'},
      details: 'Modal verb expressing desire or intention.'},
    { id: 2029, level: 'A1', infinitive: 'dürfen', english: 'to be allowed to', pronunciation: 'DÜR-fen',
      conjugation: {ich: 'darf', du: 'darfst', 'er/sie/es': 'darf', wir: 'dürfen', ihr: 'dürft', 'sie/Sie': 'dürfen'},
      partizipII: 'gedurft', perfectAux: 'haben', prateritum: 'durfte',
      acceptedMeanings: ['may','be allowed to','allowed'],
      example: {de: 'Darf ich gehen?', en: 'May I go?'},
      details: 'Modal verb expressing permission. In negative contexts it can indicate prohibition.'},
    { id: 2030, level: 'A1', infinitive: 'sollen', english: 'should/to be supposed to', pronunciation: 'SOL-len',
      conjugation: {ich: 'soll', du: 'sollst', 'er/sie/es': 'soll', wir: 'sollen', ihr: 'sollt', 'sie/Sie': 'sollen'},
      partizipII: 'gesollt', perfectAux: 'haben', prateritum: 'sollte',
      acceptedMeanings: ['should','ought to'],
      example: {de: 'Ich soll mehr Gemüse essen.', en: 'I should eat more vegetables.'},
      details: 'Modal verb often indicating advice or reported obligations.'},
    { id: 2031, level: 'A1', infinitive: 'stehen', english: 'to stand', pronunciation: 'SHTAY-en',
      conjugation: {ich: 'stehe', du: 'stehst', 'er/sie/es': 'steht', wir: 'stehen', ihr: 'steht', 'sie/Sie': 'stehen'},
      partizipII: 'gestanden', perfectAux: 'haben', prateritum: 'stand',
      acceptedMeanings: ['stand'],
      example: {de: 'Ich stehe am Fenster.', en: 'I stand at the window.'},
      details: 'Irregular past forms. Essential for describing position.'},
    { id: 2032, level: 'A1', infinitive: 'sitzen', english: 'to sit', pronunciation: 'ZIT-zen',
      conjugation: {ich: 'sitze', du: 'sitzt', 'er/sie/es': 'sitzt', wir: 'sitzen', ihr: 'sitzt', 'sie/Sie': 'sitzen'},
      partizipII: 'gesessen', perfectAux: 'haben', prateritum: 'saß',
      acceptedMeanings: ['sit'],
      example: {de: 'Ich sitze auf dem Stuhl.', en: 'I sit on the chair.'},
      details: 'Irregular past forms. Essential for describing position.'},
    { id: 2033, level: 'A1', infinitive: 'verlieren', english: 'to lose', pronunciation: 'fer-LEE-ren',
      conjugation: {ich: 'verliere', du: 'verlierst', 'er/sie/es': 'verliert', wir: 'verlieren', ihr: 'verliert', 'sie/Sie': 'verlieren'},
      partizipII: 'verloren', perfectAux: 'haben', prateritum: 'verlor',
      acceptedMeanings: ['lose'],
      example: {de: 'Ich verliere meinen Schlüssel.', en: 'I lose my key.'},
      details: 'Stem-changing verb: ie→i in du/er forms. Essential for daily situations.'},
    { id: 2034, level: 'A1', infinitive: 'gewinnen', english: 'to win', pronunciation: 'ge-VIN-nen',
      conjugation: {ich: 'gewinne', du: 'gewinnst', 'er/sie/es': 'gewinnt', wir: 'gewinnen', ihr: 'gewinnt', 'sie/Sie': 'gewinnen'},
      partizipII: 'gewonnen', perfectAux: 'haben', prateritum: 'gewann',
      acceptedMeanings: ['win'],
      example: {de: 'Ich gewinne das Spiel.', en: 'I win the game.'},
      details: 'Stem-changing verb: i→a in past forms. Used in sports and competitions.'},
    { id: 2035, level: 'A1', infinitive: 'werfen', english: 'to throw', pronunciation: 'VER-fen',
      conjugation: {ich: 'werfe', du: 'wirfst', 'er/sie/es': 'wirft', wir: 'werfen', ihr: 'werft', 'sie/Sie': 'werfen'},
      partizipII: 'geworfen', perfectAux: 'haben', prateritum: 'warf',
      acceptedMeanings: ['throw'],
      example: {de: 'Ich werfe den Ball.', en: 'I throw the ball.'},
      details: 'Stem-changing verb: e→i in du/er forms. Used in sports and daily activities.'},
    { id: 2036, level: 'A1', infinitive: 'schließen', english: 'to close', pronunciation: 'SHLEE-sen',
      conjugation: {ich: 'schließe', du: 'schließt', 'er/sie/es': 'schließt', wir: 'schließen', ihr: 'schließt', 'sie/Sie': 'schließen'},
      partizipII: 'geschlossen', perfectAux: 'haben', prateritum: 'schloss',
      acceptedMeanings: ['close','shut'],
      example: {de: 'Ich schließe die Tür.', en: 'I close the door.'},
      details: 'Stem-changing verb: ie→o in past forms. Essential for daily activities.'},
    
    // A2 Irregular Verbs from Goethe A2 WortListe
    { id: 2101, level: 'A2', infinitive: 'anfangen', english: 'to begin', pronunciation: 'AN-fang-en',
      conjugation: {ich: 'fange an', du: 'fängst an', 'er/sie/es': 'fängt an', wir: 'fangen an', ihr: 'fangt an', 'sie/Sie': 'fangen an'},
      partizipII: 'angefangen', perfectAux: 'haben', prateritum: 'fing an',
      acceptedMeanings: ['begin','start'],
      example: {de: 'Ich fange um 9 Uhr an.', en: 'I begin at 9 o\'clock.'},
      details: 'Separable verb with irregular past forms. Essential for describing start times.'},
    { id: 2102, level: 'A2', infinitive: 'beginnen', english: 'to begin', pronunciation: 'be-GIN-nen',
      conjugation: {ich: 'beginne', du: 'beginnst', 'er/sie/es': 'beginnt', wir: 'beginnen', ihr: 'beginnt', 'sie/Sie': 'beginnen'},
      partizipII: 'begonnen', perfectAux: 'haben', prateritum: 'begann',
      acceptedMeanings: ['begin','start'],
      example: {de: 'Der Film beginnt um 20 Uhr.', en: 'The film begins at 8 PM.'},
      details: 'Irregular past forms. Used for events and activities starting.'},
    { id: 2103, level: 'A2', infinitive: 'backen', english: 'to bake', pronunciation: 'BAH-ken',
      conjugation: {ich: 'backe', du: 'bäckst', 'er/sie/es': 'bäckt', wir: 'backen', ihr: 'backt', 'sie/Sie': 'backen'},
      partizipII: 'gebacken', perfectAux: 'haben', prateritum: 'buk / backte',
      acceptedMeanings: ['bake'],
      example: {de: 'Ich backe einen Kuchen.', en: 'I bake a cake.'},
      details: 'Stem-changing verb: a→ä in du/er forms. Both regular and irregular past forms accepted.'},
    { id: 2104, level: 'A2', infinitive: 'fallen', english: 'to fall', pronunciation: 'FAH-len',
      conjugation: {ich: 'falle', du: 'fällst', 'er/sie/es': 'fällt', wir: 'fallen', ihr: 'fallt', 'sie/Sie': 'fallen'},
      partizipII: 'gefallen', perfectAux: 'sein', prateritum: 'fiel',
      acceptedMeanings: ['fall'],
      example: {de: 'Ich falle hin.', en: 'I fall down.'},
      details: 'Stem-changing verb: a→ä in du/er forms. Uses "sein" as auxiliary.'},
    { id: 2105, level: 'A2', infinitive: 'fangen', english: 'to catch', pronunciation: 'FANG-en',
      conjugation: {ich: 'fange', du: 'fängst', 'er/sie/es': 'fängt', wir: 'fangen', ihr: 'fangt', 'sie/Sie': 'fangen'},
      partizipII: 'gefangen', perfectAux: 'haben', prateritum: 'fing',
      acceptedMeanings: ['catch'],
      example: {de: 'Ich fange den Ball.', en: 'I catch the ball.'},
      details: 'Stem-changing verb: a→ä in du/er forms. Used in sports and daily activities.'},
    { id: 2106, level: 'A2', infinitive: 'empfehlen', english: 'to recommend', pronunciation: 'emp-FAY-len',
      conjugation: {ich: 'empfehle', du: 'empfiehlst', 'er/sie/es': 'empfiehlt', wir: 'empfehlen', ihr: 'empfehlt', 'sie/Sie': 'empfehlen'},
      partizipII: 'empfohlen', perfectAux: 'haben', prateritum: 'empfahl',
      acceptedMeanings: ['recommend','suggest'],
      example: {de: 'Ich empfehle dieses Restaurant.', en: 'I recommend this restaurant.'},
      details: 'Stem-changing verb: e→ie in du/er forms. Essential for giving advice.'},
    { id: 2107, level: 'A2', infinitive: 'gefallen', english: 'to please', pronunciation: 'ge-FAH-len',
      conjugation: {ich: 'gefall', du: 'gefallst', 'er/sie/es': 'gefallt', wir: 'gefallen', ihr: 'gefallt', 'sie/Sie': 'gefallen'},
      partizipII: 'gefallen', perfectAux: 'haben', prateritum: 'gefiel',
      acceptedMeanings: ['please','like'],
      example: {de: 'Das gefällt mir.', en: 'I like that.'},
      details: 'Takes dative object. Used to express liking or preference.'},
    { id: 2108, level: 'A2', infinitive: 'gelten', english: 'to be valid', pronunciation: 'GEL-ten',
      conjugation: {ich: 'gelte', du: 'giltst', 'er/sie/es': 'gilt', wir: 'gelten', ihr: 'geltet', 'sie/Sie': 'gelten'},
      partizipII: 'gegolten', perfectAux: 'haben', prateritum: 'galt',
      acceptedMeanings: ['be valid','apply'],
      example: {de: 'Das gilt nicht mehr.', en: 'That is no longer valid.'},
      details: 'Highly irregular verb. Used for rules, regulations, and validity.'},
    { id: 2109, level: 'A2', infinitive: 'genießen', english: 'to enjoy', pronunciation: 'ge-NEE-sen',
      conjugation: {ich: 'genieße', du: 'genießt', 'er/sie/es': 'genießt', wir: 'genießen', ihr: 'genießt', 'sie/Sie': 'genießen'},
      partizipII: 'genossen', perfectAux: 'haben', prateritum: 'genoss',
      acceptedMeanings: ['enjoy'],
      example: {de: 'Ich genieße das Essen.', en: 'I enjoy the food.'},
      details: 'Stem-changing verb: ie→o in past forms. Used for pleasure and enjoyment.'},
    { id: 2110, level: 'A2', infinitive: 'gießen', english: 'to pour/water', pronunciation: 'GEE-sen',
      conjugation: {ich: 'gieße', du: 'gießt', 'er/sie/es': 'gießt', wir: 'gießen', ihr: 'gießt', 'sie/Sie': 'gießen'},
      partizipII: 'gegossen', perfectAux: 'haben', prateritum: 'goss',
      acceptedMeanings: ['pour','water'],
      example: {de: 'Ich gieße die Blumen.', en: 'I water the flowers.'},
      details: 'Stem-changing verb: ie→o in past forms. Used for liquids and plants.'},
    { id: 2111, level: 'A2', infinitive: 'halten', english: 'to hold/stop', pronunciation: 'HAL-ten',
      conjugation: {ich: 'halte', du: 'hältst', 'er/sie/es': 'hält', wir: 'halten', ihr: 'haltet', 'sie/Sie': 'halten'},
      partizipII: 'gehalten', perfectAux: 'haben', prateritum: 'hielt',
      acceptedMeanings: ['hold','stop'],
      example: {de: 'Ich halte den Schlüssel.', en: 'I hold the key.'},
      details: 'Stem-changing verb: a→ä in du/er forms. Essential for physical actions.'},
    { id: 2112, level: 'A2', infinitive: 'heben', english: 'to lift', pronunciation: 'HAY-ben',
      conjugation: {ich: 'hebe', du: 'hebst', 'er/sie/es': 'hebt', wir: 'heben', ihr: 'hebt', 'sie/Sie': 'heben'},
      partizipII: 'gehoben', perfectAux: 'haben', prateritum: 'hob',
      acceptedMeanings: ['lift','raise'],
      example: {de: 'Ich hebe die Tasche.', en: 'I lift the bag.'},
      details: 'Strong verb with vowel change in past forms. Used for physical actions.'},
    { id: 2113, level: 'A2', infinitive: 'lassen', english: 'to let/leave', pronunciation: 'LAH-sen',
      conjugation: {ich: 'lasse', du: 'lässt', 'er/sie/es': 'lässt', wir: 'lassen', ihr: 'lasst', 'sie/Sie': 'lassen'},
      partizipII: 'gelassen', perfectAux: 'haben', prateritum: 'ließ',
      acceptedMeanings: ['let','leave','allow'],
      example: {de: 'Ich lasse dich gehen.', en: 'I let you go.'},
      details: 'Stem-changing verb: a→ä in du/er forms. Essential for permission and causation.'},
    { id: 2114, level: 'A2', infinitive: 'leihen', english: 'to lend/borrow', pronunciation: 'LY-en',
      conjugation: {ich: 'leihe', du: 'leihst', 'er/sie/es': 'leiht', wir: 'leihen', ihr: 'leiht', 'sie/Sie': 'leihen'},
      partizipII: 'geliehen', perfectAux: 'haben', prateritum: 'lieh',
      acceptedMeanings: ['lend','borrow'],
      example: {de: 'Ich leihe dir das Buch.', en: 'I lend you the book.'},
      details: 'Strong verb with vowel change in past forms. Used for borrowing and lending.'},
    { id: 2115, level: 'A2', infinitive: 'liegen', english: 'to lie (be located)', pronunciation: 'LEE-gen',
      conjugation: {ich: 'liege', du: 'liegst', 'er/sie/es': 'liegt', wir: 'liegen', ihr: 'liegt', 'sie/Sie': 'liegen'},
      partizipII: 'gelegen', perfectAux: 'haben', prateritum: 'lag',
      acceptedMeanings: ['lie','be located'],
      example: {de: 'Das Buch liegt auf dem Tisch.', en: 'The book lies on the table.'},
      details: 'Strong verb with vowel change in past forms. Used for location and position.'},
    { id: 2116, level: 'A2', infinitive: 'lügen', english: 'to lie (tell untruth)', pronunciation: 'LÜ-gen',
      conjugation: {ich: 'lüge', du: 'lügst', 'er/sie/es': 'lügt', wir: 'lügen', ihr: 'lügt', 'sie/Sie': 'lügen'},
      partizipII: 'gelogen', perfectAux: 'haben', prateritum: 'log',
      acceptedMeanings: ['lie','tell untruth'],
      example: {de: 'Du lügst.', en: 'You are lying.'},
      details: 'Strong verb with vowel change in past forms. Distinguish from "liegen" (to lie down).'},
    { id: 2117, level: 'A2', infinitive: 'reiten', english: 'to ride', pronunciation: 'RY-ten',
      conjugation: {ich: 'reite', du: 'reitest', 'er/sie/es': 'reitet', wir: 'reiten', ihr: 'reitet', 'sie/Sie': 'reiten'},
      partizipII: 'geritten', perfectAux: 'haben', prateritum: 'ritt',
      acceptedMeanings: ['ride'],
      example: {de: 'Ich reite ein Pferd.', en: 'I ride a horse.'},
      details: 'Strong verb with vowel change in past forms. Used for horseback riding.'},
    { id: 2118, level: 'A2', infinitive: 'riechen', english: 'to smell', pronunciation: 'REE-khen',
      conjugation: {ich: 'rieche', du: 'riechst', 'er/sie/es': 'riecht', wir: 'riechen', ihr: 'riecht', 'sie/Sie': 'riechen'},
      partizipII: 'gerochen', perfectAux: 'haben', prateritum: 'roch',
      acceptedMeanings: ['smell'],
      example: {de: 'Das riecht gut.', en: 'That smells good.'},
      details: 'Strong verb with vowel change in past forms. Used for sensory perception.'},
    { id: 2119, level: 'A2', infinitive: 'rufen', english: 'to shout/call', pronunciation: 'ROO-fen',
      conjugation: {ich: 'rufe', du: 'rufst', 'er/sie/es': 'ruft', wir: 'rufen', ihr: 'ruft', 'sie/Sie': 'rufen'},
      partizipII: 'gerufen', perfectAux: 'haben', prateritum: 'rief',
      acceptedMeanings: ['shout','call'],
      example: {de: 'Ich rufe dich an.', en: 'I call you.'},
      details: 'Strong verb with vowel change in past forms. Used for communication.'},
    { id: 2120, level: 'A2', infinitive: 'raten', english: 'to advise/guess', pronunciation: 'RAH-ten',
      conjugation: {ich: 'rate', du: 'rätst', 'er/sie/es': 'rät', wir: 'raten', ihr: 'ratet', 'sie/Sie': 'raten'},
      partizipII: 'geraten', perfectAux: 'haben', prateritum: 'riet',
      acceptedMeanings: ['advise','guess'],
      example: {de: 'Ich rate dir zu gehen.', en: 'I advise you to go.'},
      details: 'Stem-changing verb: a→ä in du/er forms. Used for advice and guessing.'},
    { id: 2121, level: 'A2', infinitive: 'reißen', english: 'to tear', pronunciation: 'RY-sen',
      conjugation: {ich: 'reiße', du: 'reißt', 'er/sie/es': 'reißt', wir: 'reißen', ihr: 'reißt', 'sie/Sie': 'reißen'},
      partizipII: 'gerissen', perfectAux: 'haben', prateritum: 'riss',
      acceptedMeanings: ['tear'],
      example: {de: 'Das Papier reißt.', en: 'The paper tears.'},
      details: 'Strong verb with vowel change in past forms. Used for physical actions.'},
    { id: 2122, level: 'A2', infinitive: 'rennen', english: 'to run (fast)', pronunciation: 'REN-nen',
      conjugation: {ich: 'renne', du: 'rennst', 'er/sie/es': 'rennt', wir: 'rennen', ihr: 'rennt', 'sie/Sie': 'rennen'},
      partizipII: 'gerannt', perfectAux: 'sein', prateritum: 'rannte',
      acceptedMeanings: ['run','run fast'],
      example: {de: 'Ich renne schnell.', en: 'I run fast.'},
      details: 'Mixed verb: regular present, irregular past. Uses "sein" as auxiliary.'},
    { id: 2123, level: 'A2', infinitive: 'schaffen', english: 'to create/achieve', pronunciation: 'SHAH-fen',
      conjugation: {ich: 'schaffe', du: 'schaffst', 'er/sie/es': 'schafft', wir: 'schaffen', ihr: 'schafft', 'sie/Sie': 'schaffen'},
      partizipII: 'geschaffen', perfectAux: 'haben', prateritum: 'schuf',
      acceptedMeanings: ['create','achieve'],
      example: {de: 'Ich schaffe das.', en: 'I can do it.'},
      details: 'Strong verb with vowel change in past forms. Used for creation and achievement.'},
    { id: 2124, level: 'A2', infinitive: 'schieben', english: 'to push', pronunciation: 'SHEE-ben',
      conjugation: {ich: 'schiebe', du: 'schiebst', 'er/sie/es': 'schiebt', wir: 'schieben', ihr: 'schiebt', 'sie/Sie': 'schieben'},
      partizipII: 'geschoben', perfectAux: 'haben', prateritum: 'schob',
      acceptedMeanings: ['push'],
      example: {de: 'Ich schiebe den Wagen.', en: 'I push the cart.'},
      details: 'Strong verb with vowel change in past forms. Used for physical movement.'},
    { id: 2125, level: 'A2', infinitive: 'schießen', english: 'to shoot', pronunciation: 'SHEE-sen',
      conjugation: {ich: 'schieße', du: 'schießt', 'er/sie/es': 'schießt', wir: 'schießen', ihr: 'schießt', 'sie/Sie': 'schießen'},
      partizipII: 'geschossen', perfectAux: 'haben', prateritum: 'schoss',
      acceptedMeanings: ['shoot'],
      example: {de: 'Ich schieße ein Tor.', en: 'I shoot a goal.'},
      details: 'Strong verb with vowel change in past forms. Used in sports and other contexts.'},
    { id: 2126, level: 'A2', infinitive: 'scheinen', english: 'to seem/shine', pronunciation: 'SHY-nen',
      conjugation: {ich: 'scheine', du: 'scheinst', 'er/sie/es': 'scheint', wir: 'scheinen', ihr: 'scheint', 'sie/Sie': 'scheinen'},
      partizipII: 'geschienen', perfectAux: 'haben', prateritum: 'schien',
      acceptedMeanings: ['seem','shine'],
      example: {de: 'Die Sonne scheint.', en: 'The sun shines.'},
      details: 'Strong verb with vowel change in past forms. Used for appearance and light.'},
    { id: 2127, level: 'A2', infinitive: 'schneiden', english: 'to cut', pronunciation: 'SHNY-den',
      conjugation: {ich: 'schneide', du: 'schneidest', 'er/sie/es': 'schneidet', wir: 'schneiden', ihr: 'schneidet', 'sie/Sie': 'schneiden'},
      partizipII: 'geschnitten', perfectAux: 'haben', prateritum: 'schnitt',
      acceptedMeanings: ['cut'],
      example: {de: 'Ich schneide das Brot.', en: 'I cut the bread.'},
      details: 'Strong verb with vowel change in past forms. Used for cutting actions.'},
    { id: 2128, level: 'A2', infinitive: 'schwimmen', english: 'to swim', pronunciation: 'SHVIM-men',
      conjugation: {ich: 'schwimme', du: 'schwimmst', 'er/sie/es': 'schwimmt', wir: 'schwimmen', ihr: 'schwimmt', 'sie/Sie': 'schwimmen'},
      partizipII: 'geschwommen', perfectAux: 'sein', prateritum: 'schwamm',
      acceptedMeanings: ['swim'],
      example: {de: 'Ich schwimme im See.', en: 'I swim in the lake.'},
      details: 'Strong verb with vowel change in past forms. Uses "sein" as auxiliary.'},
    { id: 2129, level: 'A2', infinitive: 'senden', english: 'to send', pronunciation: 'ZEN-den',
      conjugation: {ich: 'sende', du: 'sendest', 'er/sie/es': 'sendet', wir: 'senden', ihr: 'sendet', 'sie/Sie': 'senden'},
      partizipII: 'gesandt / gesendet', perfectAux: 'haben', prateritum: 'sandte / sendete',
      acceptedMeanings: ['send'],
      example: {de: 'Ich sende eine E-Mail.', en: 'I send an email.'},
      details: 'Mixed verb: both regular and irregular forms accepted. Used for communication.'},
    { id: 2130, level: 'A2', infinitive: 'singen', english: 'to sing', pronunciation: 'ZING-en',
      conjugation: {ich: 'singe', du: 'singst', 'er/sie/es': 'singt', wir: 'singen', ihr: 'singt', 'sie/Sie': 'singen'},
      partizipII: 'gesungen', perfectAux: 'haben', prateritum: 'sang',
      acceptedMeanings: ['sing'],
      example: {de: 'Ich singe ein Lied.', en: 'I sing a song.'},
      details: 'Strong verb with vowel change in past forms. Used for musical activities.'},
    { id: 2131, level: 'A2', infinitive: 'sinken', english: 'to sink', pronunciation: 'ZIN-ken',
      conjugation: {ich: 'sinke', du: 'sinkst', 'er/sie/es': 'sinkt', wir: 'sinken', ihr: 'sinkt', 'sie/Sie': 'sinken'},
      partizipII: 'gesunken', perfectAux: 'sein', prateritum: 'sank',
      acceptedMeanings: ['sink'],
      example: {de: 'Das Schiff sinkt.', en: 'The ship sinks.'},
      details: 'Strong verb with vowel change in past forms. Uses "sein" as auxiliary.'},
    { id: 2132, level: 'A2', infinitive: 'stehlen', english: 'to steal', pronunciation: 'SHTAY-len',
      conjugation: {ich: 'stehle', du: 'stiehlst', 'er/sie/es': 'stiehlt', wir: 'stehlen', ihr: 'stehlt', 'sie/Sie': 'stehlen'},
      partizipII: 'gestohlen', perfectAux: 'haben', prateritum: 'stahl',
      acceptedMeanings: ['steal'],
      example: {de: 'Er stiehlt das Geld.', en: 'He steals the money.'},
      details: 'Stem-changing verb: e→ie in du/er forms. Strong verb in past forms.'},
    { id: 2133, level: 'A2', infinitive: 'steigen', english: 'to climb', pronunciation: 'SHTY-gen',
      conjugation: {ich: 'steige', du: 'steigst', 'er/sie/es': 'steigt', wir: 'steigen', ihr: 'steigt', 'sie/Sie': 'steigen'},
      partizipII: 'gestiegen', perfectAux: 'sein', prateritum: 'stieg',
      acceptedMeanings: ['climb'],
      example: {de: 'Ich steige auf den Berg.', en: 'I climb the mountain.'},
      details: 'Strong verb with vowel change in past forms. Uses "sein" as auxiliary.'},
    { id: 2134, level: 'A2', infinitive: 'stoßen', english: 'to push/knock', pronunciation: 'SHTO-sen',
      conjugation: {ich: 'stoße', du: 'stößt', 'er/sie/es': 'stößt', wir: 'stoßen', ihr: 'stoßt', 'sie/Sie': 'stoßen'},
      partizipII: 'gestoßen', perfectAux: 'haben', prateritum: 'stieß',
      acceptedMeanings: ['push','knock'],
      example: {de: 'Ich stoße an die Tür.', en: 'I knock on the door.'},
      details: 'Stem-changing verb: o→ö in du/er forms. Strong verb in past forms.'},
    { id: 2135, level: 'A2', infinitive: 'treiben', english: 'to drive (sports)/float', pronunciation: 'TRY-ben',
      conjugation: {ich: 'treibe', du: 'treibst', 'er/sie/es': 'treibt', wir: 'treiben', ihr: 'treibt', 'sie/Sie': 'treiben'},
      partizipII: 'getrieben', perfectAux: 'haben', prateritum: 'trieb',
      acceptedMeanings: ['drive','float'],
      example: {de: 'Ich treibe Sport.', en: 'I do sports.'},
      details: 'Strong verb with vowel change in past forms. Used for sports and movement.'},
    { id: 2136, level: 'A2', infinitive: 'verzeihen', english: 'to forgive', pronunciation: 'fer-TSY-en',
      conjugation: {ich: 'verzeihe', du: 'verzeihst', 'er/sie/es': 'verzeiht', wir: 'verzeihen', ihr: 'verzeiht', 'sie/Sie': 'verzeihen'},
      partizipII: 'verziehen', perfectAux: 'haben', prateritum: 'verzieh',
      acceptedMeanings: ['forgive'],
      example: {de: 'Ich verzeihe dir.', en: 'I forgive you.'},
      details: 'Strong verb with vowel change in past forms. Used for forgiveness.'},
    { id: 2137, level: 'A2', infinitive: 'wachsen', english: 'to grow', pronunciation: 'VAH-ksen',
      conjugation: {ich: 'wachse', du: 'wächst', 'er/sie/es': 'wächst', wir: 'wachsen', ihr: 'wachst', 'sie/Sie': 'wachsen'},
      partizipII: 'gewachsen', perfectAux: 'sein', prateritum: 'wuchs',
      acceptedMeanings: ['grow'],
      example: {de: 'Die Pflanze wächst.', en: 'The plant grows.'},
      details: 'Stem-changing verb: a→ä in du/er forms. Uses "sein" as auxiliary.'},
    { id: 2138, level: 'A2', infinitive: 'weisen', english: 'to point', pronunciation: 'VY-zen',
      conjugation: {ich: 'weise', du: 'weist', 'er/sie/es': 'weist', wir: 'weisen', ihr: 'weist', 'sie/Sie': 'weisen'},
      partizipII: 'gewiesen', perfectAux: 'haben', prateritum: 'wies',
      acceptedMeanings: ['point'],
      example: {de: 'Ich weise auf das Problem hin.', en: 'I point to the problem.'},
      details: 'Strong verb with vowel change in past forms. Used for indicating direction.'}
  ]
};


